title: Nikko Samson
logo: "/images/ns_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Passionate about data science.
  <br><br>
  <a href="https://www.linkedin.com/in/nikkosamson/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
